### ISSUE TITLE
Style brackets for html syntax

### ISSUE THREAD

**Issue by jacobarriola** [wesbos/cobalt2-atom#10]
Hey Wes,

Would love to get the #fff color on the `<` and `>` brackets like the Sublime version has. Not sure the best way I can contribute or submit a PR.  I've tried editing the less stylesheet w/out any luck.

Thanks!

 The atom version 👇
![image](https://cloud.githubusercontent.com/assets/1371573/16974498/02ecbeac-4df2-11e6-8b7a-135b95dd9a62.png)

The Sublime version 👇
![image](https://cloud.githubusercontent.com/assets/1371573/16974517/328626ee-4df2-11e6-9db9-8c771cd49506.png)

**Comment by rosston** [comment]
Atom theme maintainer here.

That shouldn't be too hard to do. I just tried removing the `.meta.tag` selector from the styles. It works great for HTML, but not quite right for XML (see below). It should just be a minor adjustment to make sure the punctuation stays white. I'll take a stab at it soon.
![screen shot 2016-07-20 at 09 09 44](https://cloud.githubusercontent.com/assets/108518/16987381/e2448da2-4e59-11e6-8d46-dca98a91dd77.png)

**Comment by jacobarriola** [comment]
Awesome @rosston - would love to back trace how you've accomplished this as well so that I can help next time. Thanks! 👏

**Comment by rosston** [comment]
cmd+alt+i (probably ctrl+alt+i not on a Mac?) will bring up the Chromium web inspector. Hacking on Atom and its packages is (almost) as easy as doing web dev work.

Once you've figured out what changes actually need to be made, you can just check out the code somewhere on your machine, make your changes, and symlink the directory into `~/.atom/packages`.

That's the super-quick-and-dirty summary of Atom (theme) hacking. 😃

**Comment by rosston** [comment]
Fixed and released in 0.3.2.
