### ISSUE TITLE
The same problem with brackets under current line bg

### ISSUE THREAD

**Issue by alcros33** [wesbos/cobalt2-atom#15]
So bracket highlight cannot be seen at current line, for the current line bg seems to be over it... I already tried changing that z-index thing (I don't know css) into many values and it pretty much changes nothing,
saw the post about it, but I have version 0.5.1 and still have this problem.

**Comment by rosston** [comment]
Fixed and released in 0.5.2.

**Comment by alcros33** [comment]
Perfect! It works just fine, thanks
