### ISSUE TITLE
highlight hide the text

### ISSUE THREAD

**Issue by eshikerya** [wesbos/cobalt2-atom#16]
selected(highlighted) text after last update(0.5.2) make text invisible
<img width="453" alt="view_js_ _components_page_ ___work_casualpm-front" src="https://user-images.githubusercontent.com/956884/32639763-0766876a-c5ce-11e7-8ff9-f7ec90c6455d.png">

**Comment by adamjoneill** [comment]
same as @eshikerya for me too

**Comment by eshikerya** [comment]
quickfix is to roolback latest commit. just to give a clue where is to dig

**Comment by rosston** [comment]
Thanks for the quick bug report! Fixed and released in 0.5.3.
