### ISSUE TITLE
[question] How to handle inline React HTML?

### ISSUE THREAD

**Issue by fjaguero** [wesbos/cobalt2-atom#2]
![Reat HTML](http://cl.ly/image/1N2M2g0H2O2h/Image%202015-07-22%20at%2011.23.50%20a.%20m..png)

I was trying the theme and then found out that it doesn't works fine with React inline's HTML.

Any idea how to remove the gradients?

Thanks.

**Comment by rosston** [comment]
Are you using [language-babel](https://atom.io/packages/language-babel) for your JSX support? That's the only way I can replicate this issue. [language-javascript-jsx](https://atom.io/packages/language-javascript-jsx) and [react](https://atom.io/packages/react) appear not to cause it.

I'll try to figure out if there's something in the theme causing the issue.

**Comment by rosston** [comment]
This appears to be an issue with how language-babel classifies JSX. I've opened an issue there: https://github.com/gandm/language-babel/issues/30

**Comment by rosston** [comment]
Closed in https://github.com/gandm/language-babel/issues/30
