### ISSUE TITLE
Not on APM anymore?

### ISSUE THREAD

**Issue by ianobermiller** [wesbos/cobalt2-atom#3]
What happened to this package? I no longer see it on APM, https://atom.io/packages/search?utf8=%E2%9C%93&q=cobalt2, and it disappeared from Atom :*(

**Comment by rosston** [comment]
Huh, you're right about the search. Neither [cobalt2](https://atom.io/packages/search?q=cobalt2) or [cobalt2-syntax](https://atom.io/packages/search?utf8=✓&q=cobalt2-syntax) work as search terms.

However! The direct link works: https://atom.io/packages/cobalt2-syntax. And `apm search cobalt2` from the CLI returns cobalt2-syntax as the top hit for me.

Not really sure what to do here.

**Comment by wesbos** [comment]
Try adding Cobalt2 to the description - it doesn't say it anywhere

**Comment by rosston** [comment]
Oh, derp, I know what the problem is. atom.io _actually_ separated package and theme search now (just like in the editor UI). So https://atom.io/themes/search?q=cobalt2 works just fine.

**Comment by ianobermiller** [comment]
Thanks for checking this out. For some reason I had to remove and reinstall cobalt2 after the most recent Atom update, and was concerned when I didn't find it.
