### ISSUE TITLE
Not support Ember handlebars syntax.

### ISSUE THREAD

**Issue by Vazgen7788** [wesbos/cobalt2-atom#4]

**Comment by rosston** [comment]
Do you have a specific example or screenshot?

**Comment by Vazgen7788** [comment]
![screenshot from 2015-11-19 09-15-10](https://cloud.githubusercontent.com/assets/8538941/11262901/d920b3a6-8e95-11e5-9c95-cf7da81c71d8.png)

**Comment by Vazgen7788** [comment]
Left Desktop is Sublime and Right is Atom

**Comment by rosston** [comment]
Sorry! I haven't been able to dig it into this yet. I'll try to figure it out this weekend.

**Comment by rosston** [comment]
In Atom, it's up to the language support package to provide the right classes for syntax themes to highlight properly.

It looks like you're using [atom-handlebars](https://atom.io/packages/atom-handlebars) for Handlebars language support, but that package [doesn't enable much syntax highlighting](https://github.com/Sneagan/atom-handlebars/issues/13).

The [handlebars package](https://atom.io/packages/handlebars) appears to be fairly well-maintained and enables syntax highlighting similar to your Sublime Text screenshot. Here's a screenshot I took of an example file: 

![handlebars](https://cloud.githubusercontent.com/assets/108518/11452977/49cd29ba-95bf-11e5-90c8-66b25bb5e96d.png)
