### ISSUE TITLE
Question: JSON Highlighting

### ISSUE THREAD

**Issue by sdempsey** [wesbos/cobalt2-atom#5]
Hi there, 

Hopefully I'm missing something and you'll be able to clear this up pretty quickly for me.  I recently switched over to atom and in setting things up noted some weird highlighting issues - specifically with my project's `.jshintrc`   I double checked that the syntax highlighting was set to JSON but the comment highlighting is a bit inconsistent with what I've seen over in the Sublime theme.  

The jshintrc
![screen shot 2016-03-01 at 11 58 33 am](https://cloud.githubusercontent.com/assets/5795146/13434863/7cd4457a-dfa5-11e5-8038-645e8661e5ab.png)

just to make sure it wasn't isolated to that file I created a small dummy JSON object:

![screen shot 2016-03-01 at 12 04 01 pm](https://cloud.githubusercontent.com/assets/5795146/13434912/b52c20dc-dfa5-11e5-9c69-afd92154617e.png)

And for posterity, what I expected (from sublime text): 
<img width="583" alt="screen shot 2016-03-01 at 12 05 37 pm" src="https://cloud.githubusercontent.com/assets/5795146/13434970/f3b73b48-dfa5-11e5-831e-b2f1d3a95acf.png">

Is there a setting I need to configure?  Anything more I can do to help?

**Comment by rosston** [comment]
Good question!

This is a result of Atom's `language-json` package that adds support for JSON. That's a core, installed-by-default package. It's up to the grammar package to put the appropriate classes on content, and it looks like `language-json` doesn't yet have support for comments in JSON. There's an open issue (https://github.com/atom/language-json/issues/28) and PR (https://github.com/atom/language-json/pull/29).

In the meantime, you can install the [language-json-comments package](https://atom.io/packages/language-json-comments) to get comment support for JSON.

**Comment by sdempsey** [comment]
Hell yeah! Thanks for the prompt reply and temporary solution!
