### ISSUE TITLE
Better Syntax for Jade

### ISSUE THREAD

**Issue by jdinartejesus** [wesbos/cobalt2-atom#6]
I'm using cobalt2-atom it's awesome. 

I would like just to recommend to improve for Jade syntax since the colors between the HTML tag and class are the same and it's hard to work it.

**Comment by rosston** [comment]
In Atom, it's up to the language support package to provide the right classes for syntax themes to highlight properly. I'm not sure what package you're using now, but you might want to check out a different one for Jade/[Pug](https://github.com/pugjs/pug/issues/2184) support.

Some options (maybe there are others?) (example snippet taken from https://github.com/pugjs/pug):
[atom-jade](https://atom.io/packages/atom-jade)
<img width="570" alt="atom-jade" src="https://cloud.githubusercontent.com/assets/108518/15448348/cb5f0a14-1f2d-11e6-9758-d8471bf7990a.png">

[language-jade](https://atom.io/packages/language-jade) (yellow highlight on first line is my cursor)
<img width="569" alt="language-jade" src="https://cloud.githubusercontent.com/assets/108518/15448352/db9ab108-1f2d-11e6-82b5-49e3283cc2e0.png">

[language-pug](https://atom.io/packages/language-pug)
<img width="566" alt="language-pug" src="https://cloud.githubusercontent.com/assets/108518/15448358/02a51266-1f2e-11e6-8567-bb4123958c01.png">

**Comment by jdinartejesus** [comment]
Cool @rosston, thanks for the recommendation. 
I'll use this one of this packages instead of atom-jade.

Once again thanks for the solutions.
Cheers!

**Comment by AndrewKubow** [comment]
"atom-jade" in my case don`t hightliting classes, it looks just grey like text, but maybe it`s depent from theme. I try few but was the same. "language-jade" nice.

**Comment by rosston** [comment]
@AndrewKubow Are you reporting an issue with Cobalt2? I just checked all three of the Jade/Pug packages I mentioned here (https://github.com/wesbos/cobalt2-atom/issues/6#issuecomment-220775329), and my screenshots are accurate using the Cobalt2 and the latest Atom (1.19.4).

**Comment by AndrewKubow** [comment]
@rosston Oh, sorry I missed that for Cobalt2, I use One Dark now.
