### ISSUE TITLE
bracket matcher doesn't show on focussed line

### ISSUE THREAD

**Issue by rosston** [wesbos/cobalt2-atom#9]
From @jonsrose in https://github.com/wesbos/cobalt2/issues/115:

> When I go to a line in the text editor and move the cursor to a bracket, the bracket does not get the bracket matcher styling (bottom border turns yellow) even though I do see the styling on the matching bracket. It appears that the background for the active editor line is in front of the bottom border.
> 
> I think this can be fixed by setting a z-index=0 on the bracket matcher css.

**Comment by rosston** [comment]
Fixed and released in 0.3.1.

**Comment by jonsrose** [comment]
Looks good thanks

**Comment by alcros33** [comment]
I have the same Issue... Even tho I'm in version 0.5.1... any idea?
